---
title: "HW 2: Due Day 2 11:59 PM"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Raster Analysis

Use Canvas to submit the HW. Both RMarkdown and the knitted html file is required for full credit.

## Task 

The National Oceanic and Atmospheric Administration's Coastal Change Analysis program produces land cover on the coast of the US. Download the 1996,2001,2006 and 2010 landcover data for the state of North Carolina from [here](https://coast.noaa.gov/ccapftp/#/). Answer the following questions and write a report summarising the findings.

- Download the county vector files using `tigris` or the Census website. How much urban land exists in each county on the NC coast? How has it changed over time?
- How have different types of wetlands changed in quantity over time?
- Where have the wetlands become more fragmented and which indices are good for measuring fragmentation of the wetlands in NC coast?
_ How is the fragmentation of wetland related to fragmentary urban development in these counties?
- Relate the population growth in each county to the wetland fragmentation. Annual population estimates at the county level can be downladed from the [National Cancer Institute](https://seer.cancer.gov/popdata/)


